spring:
  application:
    name: GREET-API
  
  boot:
    admin:
      client:
        url: http://localhost:8030/
  
    
#server:
#  port: 2222
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
 
# This Welcome API config as a CLient to Eureka Server         
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka