server:
  port: 7171
spring:
  application:
    name: 34_CONFIG_SERVER_APP
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashokitschool/configuration_properties
          clone-on-start: true