server:
  port: 3333

spring:
  cloud:
    gateway:
      routes:
      - id: welcome-api
        uri: lb://WELCOME-API
        predicates:
        - Path=/api1/**
      - id: greet-api
        uri: lb://GREET-API
        predicates:
        - Path=/api2/**
  
  application:
    name: API-GATEWAY
#  main:
#    web-application-type: reactive
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

      